name: netbert
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.1=
  - blosc=1.16.3
  - boto3=1.11.13
  - botocore=1.14.13
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.13.2
  - chardet=3.0.4
  - chart-studio=1.0.0
  - colorlover=0.3.0
  - cryptography=2.8
  - cudatoolkit=9.0
  - cudnn=7.6.5
  - cufflinks-py=0.17.3
  - cupti=9.0.176
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.9.1
  - future=0.18.2
  - gast=0.3.3
  - gettext=0.19.8.1
  - glib=2.58.3
  - google-pasta=0.1.8
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jmespath=0.9.4
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.0.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=4.0.1
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - ninja=1.9.0
  - nltk=3.4.5
  - nodejs=12.4.0
  - notebook=6.0.3
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - plotly=4.5.4
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.6.10
  - python-cufflinks=0.17.3
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.1.0
  - pytz=2019.3
  - qt=5.9.7
  - readline=7.0
  - regex=2020.1.8
  - requests=2.22.0
  - retrying=1.3.3
  - s3transfer=0.3.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - sip=4.19.8
  - six=1.14.0
  - snappy=1.1.7
  - sqlite=3.31.1
  - tensorboard=1.14.0
  - tensorboardx=2.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.0.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - apex
    - astunparse==1.6.3
    - beautifulsoup4==4.8.2
    - bert-serving-client==1.9.9
    - bert-serving-server==1.9.9
    - blis==0.4.1
    - cachetools==4.0.0
    - catalogue==1.0.0
    - click==7.0
    - cymem==2.0.3
    - dataclasses==0.7
    - elasticsearch==7.0.4
    - faiss==1.5.3
    - faiss-gpu==1.6.3
    - filelock==3.0.12
    - ftfy==5.7
    - google-auth==1.11.3
    - google-auth-oauthlib==0.4.1
    - gputil==1.4.0
    - grpcio==1.27.2
    - itsdangerous==1.1.0
    - keras==2.3.1
    - murmurhash==1.0.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.0
    - pandas==0.25.1
    - plac==1.1.3
    - preshed==3.0.2
    - pyarrow==0.16.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-levenshtein==0.12.0
    - pyyaml==5.3
    - pyzmq==18.1.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sacremoses==0.0.38
    - sentencepiece
    - seqeval==0.0.12
    - setuptools==45.2.0
    - soupsieve==2.0
    - spacy==2.2.4
    - srsly==1.0.2
    - tb-nightly==2.2.0a20200320
    - tensorboard-plugin-wit==1.6.0.post2
    - tf-estimator-nightly==2.3.0.dev2020032001
    - tf-nightly==2.2.0.dev20200319
    - thinc==7.4.0
    - tika==1.24
    - tokenizers==0.5.2
    - transformers==2.7.0
    - wasabi==0.6.0
    - wget==3.2
    - wordcloud==1.6.0
